// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpotifyChart.Data;

namespace SpotifyChart.Migrations
{
    [DbContext(typeof(SongsContext))]
    partial class SongsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SpotifyChart.Data.Entities.Songs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Acousticness");

                    b.Property<string>("Artist");

                    b.Property<decimal>("Danceability");

                    b.Property<double>("Duration");

                    b.Property<decimal>("Energy");

                    b.Property<decimal>("Instrumentalness");

                    b.Property<int>("Key");

                    b.Property<decimal>("Liveness");

                    b.Property<decimal>("Loudness");

                    b.Property<int>("Mode");

                    b.Property<string>("Name");

                    b.Property<int>("Rank");

                    b.Property<decimal>("Speechiness");

                    b.Property<decimal>("Tempo");

                    b.Property<int>("TimeSignature");

                    b.Property<decimal>("Valence");

                    b.HasKey("Id");

                    b.ToTable("Songs");
                });
#pragma warning restore 612, 618
        }
    }
}
